### ISSUE TITLE
adapt to use Github Enterprise?

### ISSUE THREAD

**Issue by lwiechec** [jutzig/github-release-plugin#16]
Hi,

how much work would it require to use this plugin in GitHub Enterprise? Looking at the sources, I can see some hard-coded URLs that point to the 'regular' github.com...

**Comment by jutzig** [comment]
Hi,

it should not be that difficult in case the rest  API is identical to that
of normal github.
The upload url needs to be made configurable and the repository id is
currently parsed from the SCM URL, so that might have to be adjusted as
well.

Best regards,
Johannes
Am 31.03.2016 15:04 schrieb "Lukasz Wiechec" <notifications@github.com>:

**Comment by lwiechec** [comment]
HI @jutzig, thanks. I have tested again with pre 1.75-SNAPSHOT of github-api and I am able to publish to my Github Enterprise; it turned out to be misconfiguration on my part.

My [pull request on Github API](https://github.com/kohsuke/github-api/pull/267) is under review, maybe it will get accepted.
